#  ##   ##   ####    ##   ##   #####              ####   ####      #####   ##   ##  #####             ##   ##   #####   ######            ######   #######    ##     ##   ## #
#  ##   ##    ##     ###  ##  ##   ##            ##  ##   ##      ##   ##  ##   ##   ## ##            ### ###  ##   ##   ##  ##           # ## #    ##   #   ####    ### ### #
#  ##   ##    ##     #### ##  #                 ##        ##      ##   ##  ##   ##   ##  ##           #######  #         ##  ##             ##      ## #    ##  ##   ####### #
#  ## # ##    ##     ## ####   #####            ##        ##      ##   ##  ##   ##   ##  ##           #######   #####    #####              ##      ####    ##  ##   ####### #
#  #######    ##     ##  ###       ##           ##        ##   #  ##   ##  ##   ##   ##  ##           ## # ##       ##   ##                 ##      ## #    ######   ## # ## #
#  ### ###    ##     ##   ##  ##   ##            ##  ##   ##  ##  ##   ##  ##   ##   ## ##            ##   ##  ##   ##   ##                 ##      ##   #  ##  ##   ##   ## #
#  ##   ##   ####    ##   ##   #####              ####   #######   #####    #####   #####             ##   ##   #####   ####               ####    #######  ##  ##   ##   ## #



- name: "Cloud MSP Initial set"
  hosts: all #ubuntu
  become: yes
  gather_facts: no

  tasks:
     ###############################
     ###### STEP 0. 백업
     
    - name: "STEP 0. Config File Backup"
      command: date +"%Y-%m-%d_%H-%M-%S"
      register: ldate

    - name: "STEP 0-1. Backup 디렉토리 생성"
      file:
        path: "/root/winsBackup_{{ ldate.stdout }}"
        state: directory

    - name: "STEP 0-2. /etc/localtime Backup"
      copy:
        src: /etc/localtime
        dest: "/root/winsBackup_{{ ldate.stdout }}/localtime"

    - name: "STEP 0-3. /etc/profile Backup"
      copy:
        src: /etc/profile
        dest: "/root/winsBackup_{{ ldate.stdout }}/profile"

    - name: "STEP 0-4. /etc/ssh/sshd_config Backup"
      copy:
        src: /etc/ssh/sshd_config
        dest: "/root/winsBackup_{{ ldate.stdout }}/sshd_config"

    #   ubuntu22.04 ftp 미설치
    - name: "STEP 0-5. /etc/ftpusers Backup"
      copy:
        src: /etc/ftpusers
        dest: "/root/winsBackup_{{ ldate.stdout }}/ftpusers"

    #   ubuntu22.04 selinux 미설치
    - name: "STEP 0-6. /etc/selinux/config Backup"
      copy:
        src: /etc/selinux/config
        dest: "/root/winsBackup_{{ ldate.stdout }}/selinux_config"

    #   ubuntu22.04 경로 다름
    - name: "STEP 0-7. /etc/chrony/chrony.conf Backup"
      copy:
        src: /etc/chrony.conf # rocky8 
        # src: /etc/chrony/chrony.conf # ubuntu 22.04
        dest: "/root/winsBackup_{{ ldate.stdout }}/chrony.conf"

     ###############################

     ###############################
     ###### STEP 1. 타임존 변경
 
    - name: "STEP 1 UTC to KST Converter"
      file:
        src: /usr/share/zoneinfo/Asia/Seoul
        dest: /etc/localtime
        owner: root
        group: root
        state: link

     ###############################



     ###############################
     ###### STEP 2. 타임존 변경        

    - name: "2. History Time Logging"
      lineinfile:
        path: /etc/profile
        line: HISTTIMEFORMAT=\"[%Y-%m-%d_%H:%M:%S]

     ###############################


     ###############################
     ###### STEP 3. root 로그인 제한

    - name: "3-1. SSH root login"
      replace:
        path: /etc/ssh/sshd_config
        regexp: 'PermitRootLogin yes' # rocky 8
        # regexp: '#PermitRootLogin prohibit-password' # ubuntu 22.04
        replace: 'PermitRootLogin no'

    - name: "3-2. SSH Password Login"        
      replace:
        path: /etc/ssh/sshd_config
        regexp: '#PasswordAuthentication yes' # rocky 8
        # regexp: '# 찾아야됨' # ubuntu 22.04
        replace: 'PasswordAuthentication yes'

    - name: "3-3. SSH Password Login"        # 이거 # 계속 추가됨
      replace:
        path: /etc/ssh/sshd_config
        regexp: 'PasswordAuthentication no' # rocky 8
        # regexp: '# 찾아야됨' # ubuntu 22.04
        replace: '#PasswordAuthentication no'


    - name: STEP 3-3 Check if PasswordAuthentication is set to no
      #shell: "grep -E '^\\s*PasswordAuthentication\\s+no' /etc/ssh/sshd_config"
      shell: "grep -E '^\s*PasswordAuthentication\s+no' /etc/ssh/sshd_config"      
      register: grep_result
      changed_when: false

    - name: STEP 3-3 Comment PasswordAuthentication if it's set to no
      replace:
        path: /etc/ssh/sshd_config
        regexp: '^\s*PasswordAuthentication\s+no'
        replace: '#PasswordAuthentication no'
      when: grep_result.rc == 0  # PasswordAuthentication이 no로 설정되어 있을 때만 변경

    - name: Display the result
      debug:
        msg: "PasswordAuthentication is now commented in sshd_config."
      when: grep_result.rc == 0  # 변경된 경우에만 출력




    - name: "3-4. SSH Password Login"        
      replace:
        path: /etc/ssh/sshd_config
        regexp: 'GSSAPIAuthentication yes' # rocky 8
        # regexp: '# 찾아야됨' # ubuntu 22.04
        replace: '#GSSAPIAuthentication yes'

     ###############################


     ###############################
     ###### STEP 4. 계정 패스워드 변경

    - name: STEP 4-1. Check if password is already set for root
      command: "grep -E '^root:[*!]' /etc/shadow"  # root 계정만 있음
      register: grep_result
      changed_when: false  # 명령이 실행되면 항상 변경으로 표시되지 않도록 함

    - name: STEP 4-2. Set password for root
      shell: "echo 'Sniper13@$' | passwd --stdin root > /dev/null"
      when: grep_result.rc != 0  # 이미 비밀번호가 설정되어 있으면 변경하지 않음

    - name: STEP 4-3. Display the result
      debug:
        msg: "Password for root is set."
      when: grep_result.rc == 0  # 이미 비밀번호가 설정되어 있으면 출력하지 않음      


     ###############################



     ###############################
     ###### STEP 5. FTP root 계정 제한

    - name: STEP 5-1. Check if root is already in /etc/ftpusers # config 파일 내용 확인
      shell: "grep '^root$' /etc/ftpusers" # 파일에 root 가 들어가있는지 확인
      register: grep_result
      changed_when: false  # 명령이 실행되면 항상 변경으로 표시되므로, 실제로 결과가 변경되었는지를 확인

    - name: STEP 5-2. Add root to /etc/ftpusers
      lineinfile:
        path: /etc/ftpusers
        line: "root"
      when: grep_result.rc != 0  # root가 이미 있는 경우에는 추가하지 않음

    - name: STEP 5-3. Display the result
      debug:
        msg: "root is now in /etc/ftpusers"
      when: grep_result.rc == 0  # root가 이미 있는 경우에만 출력



     ###############################


     ###############################
     ###### STEP 6. Selinux 비활성화

    - name: "STEP 6. Selinux Disable" # config 파일 수정
      replace:
        path: /etc/selinux/config
        regexp: 'SELINUX=enforcing'
        replace: 'SELINUX=disabled'



     ###############################
     ###### STEP 7. firewalld 비활성화

    - name: "7-1. Firewalld Disable" # firewalld 서비스 중지
      systemd:
        name: firewalld
        state: stopped
      ignore_errors: true  # 만약 서비스가 이미 중지되어 있어도 오류를 무시

    - name: "7-2. Display the result" # 서비스 중지 메시지 출력
      debug:
        msg: "The service '{{ firewalld }}' is stopped."




     ###############################             

     ###############################
     ###### STEP 8. 네트워크 기본 툴 패키지 설치
     
    - name: "STEP 8-1. Network Tool Install" # dnf로 패키지 설치
      dnf:
        name: iputils, net-tools, tcpdump
        state: latest # 최신버전이 아니면 업데이트도 진행
        # state: present # 설치 확인만     
      
    - name: "STEP 8-2. Check if the RPM is installed"
      command: "rpm -q iputils,net-tools,tcpdump"
      register: rpm_check_result
      ignore_errors: true  # RPM이 설치되어 있지 않으면 오류를 무시

    - name: "STEP 8-3. Display the result"
      debug:
        msg: "The RPM is {{ 'installed' if rpm_check_result.rc == 0 else 'not installed' }}" 

     ###############################


     ###############################
     ###### STEP 9. NTP 설정

    - name: "STEP 9-1. NTP Client Configuration -1" # 기본 ntp 설정 주석
      replace:
        path: /etc/chrony.conf
        regexp: 'pool 2.rocky.pool.ntp.org iburst'
        replace: '#pool 2.rocky.pool.ntp.org iburst'

    - name: "STEP 9-2. NTP Client Configuration -2" # time.bora.net 추가
      lineinfile:
        path: /etc/chrony.conf
        insertafter: '#pool 2.rocky.pool.ntp.org iburst'
        line: "server time.bora.net iburst"
